# Checking Dice

In [1]:
%env SM_FRAMEWORK=tf.keras

import segmentation_models as sm
import cv2
from skimage.io import imread, imsave
import numpy as np
import glob
import os

#from sklearn.metrics import jaccard_score


env: SM_FRAMEWORK=tf.keras


2022-07-29 22:00:43.153262: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-29 22:00:43.153282: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Segmentation Models: using `tf.keras` framework.


In [6]:
def dice(y_pred, y_true, k = 1):
    intersection = np.sum(y_pred[y_true==k]) * 2.0
    dice = intersection / (np.sum(y_pred) + np.sum(y_true))
    return dice


In [18]:
y_true = cv2.imread('/media/sda2/home/j/Downloads/0del/00/iv/Recortes/E/A_0001.png')
#y_pred = cv2.imread('/media/sda2/home/j/Dropbox_maestral/ufu/2022/iv/Recortes/E/A_0001.png')

y_pred = cv2.imread('/media/sda2/home/j/Downloads/0del/00/iv/Recortes/E/A_0001.png')

print(y_true[0][0])

#0 - 255
#dice_score = dice(y_pred, y_true, k = 255) # k can be 255 or 1

y_true = y_true / 255
y_pred = y_pred / 255

# 0 - 1
dice_score = dice(y_pred, y_true, k = 1) # k can be 255 or 1

print ("Dice Similarity: {}".format(dice_score))

[108 139 154]
Dice Similarity: 0.0


In [ ]:
print(type(y_pred))
print(y_pred.dtype)
print(y_pred.shape)
print(len(y_pred.shape))
print(y_pred)

In [52]:
#img = cv2.imread('/media/sda2/home/j/Downloads/0del/00/iv/Recortes/E/A_0001.png')
#img = cv2.imread('/media/sda2/home/j/Downloads/0del/00/iv/Recortes/E/A_0001.png', 0)
img = cv2.imread('/media/sda2/home/j/Downloads/0del/00/iv/Recortes/E/A_0001.png', cv2.IMREAD_UNCHANGED)
#img = cv2.imread('/media/sda2/home/j/Downloads/0del/00/iv/Recortes/E_mask/A_0001.png', cv2.IMREAD_UNCHANGED)
#img = cv2.imread('/media/sda2/home/j/Downloads/0del/00/iv/Recortes/E_mask/a.png', cv2.IMREAD_UNCHANGED)

print(img.shape)

B, G, R = cv2.split(img)

print(img.shape)
#if len(img.shape) == 3: # img with 3 channels
    #img = np.expand_dims(img, axis=0)
 #   img = np.expand_dims(img, axis=-1)

print(img.shape)
print(img[100][50])

print(img[0,0])

img = np.dstack((img, B))
img = np.dstack((img, B))
print(img.shape)

print(img[0,0])


(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
[ 83 139 124]
[108 139 154]
(256, 256, 5)
[108 139 154 108 108]


In [50]:
pathStart="/run/media/j/tmp_ntfs/0_t_mest_bkp/tests/Segmentacao Linha Plantio CNN/"

diretorio_pr = pathStart + "Teste_01E/result-images/"

for i in range(1): #
    if i == 0:
        dataset = 'A'
    elif i == 1:
        dataset = 'B'
    elif i == 2:
        dataset = 'C'
    elif i == 3:
        dataset = 'D'

    print("dataset:", dataset)

    #dataset = "C" 
    diretorio_mask= pathStart + "Recortes/Base_" + dataset + "_mask/"

    dice_score_all = 0
    count = 0

    for name_pr in sorted(glob.glob(diretorio_pr + dataset + "*.png")):
        img_pr = cv2.imread(name_pr)
    
        name_mask = name_pr.split("/")[-1]
        img_mask = cv2.imread(diretorio_mask + name_mask)
    
        #print("Image predict path:", name_pr)
        #print("Image mask path:", diretorio_mask + name_mask)
    
        img_pr = img_pr / 255
        #img_pr = img_pr.astype('uint8')
    
        img_mask = img_mask / 255
        #img_mask = img_mask.astype('uint8')
    
    
        dice_score = dice(img_pr, img_mask, k = 1) # k can be 255 or 1
        #print ("Dice Similarity {} : {}".format(name_mask, dice_score))
        #input()
    
        dice_score_all += dice_score
        count += 1

    print("count:", count)
    print("dice_score_all:", dice_score_all)
    print("dice_score avg:", dice_score_all/count)

print("Done all!")

dataset: A
count: 678
dice_score_all: 647.7298279265892
dice_score avg: 0.9553537285052939
Done all!


In [58]:
def img_mask_adjust(img):
    img = img / 255
    img = np.array(img)

    print(img.shape)
    img = img[:,:, 0]
    print(img.shape)

    img[img >= 0.5] = 1
    img[img < 1] = 0
    img = img.astype('uint8')

    return img


In [90]:

path_pr = "/run/media/j/tmp_ntfs/0_t_mest_bkp/tests/Segmentacao Linha Plantio CNN/Teste_01E/result-images/"
path_mask = "/run/media/j/tmp_ntfs/0_t_mest_bkp/tests/Segmentacao Linha Plantio CNN/Recortes/Base_A_mask/"

numberImg = "0001"
#numberImg = "0678"
#numberImg = "0611"

img_pr = cv2.imread(path_pr + "A_" + numberImg + ".png")
img_mask = cv2.imread(path_mask + "A_" + numberImg + ".png")

print("img_pr.shape", img_pr.shape)
print("img_mask.shape", img_mask.shape)

img_pr = img_pr / 255
img_pr = np.array(img_pr)

img_mask = img_mask[:,:, 0]
print(img_mask.shape)

img_pr = img_pr[:,:, 0]
print(img_pr.shape)

#img_pr[img_pr >= 0.5] = 1
#img_pr[img_pr < 1] = 0
img_pr = img_pr.astype('uint8')

img_mask = img_mask / 255
img_mask = img_mask.astype('uint8')

#img_mask = img_mask_adjust(img_mask)
#img_pr = img_mask_adjust(img_pr)

k = 1

dice_score = dice(img_pr, img_mask, k) # k can be 255 or 1
print ("Dice Similarity {} : {}".format("A_"+ numberImg + ".png", dice_score))

intersection = np.sum(img_pr[img_mask==k]) * 2.0
print("intersection:", intersection)

dice_val = intersection / (np.sum(img_pr) + np.sum(img_mask))
print("dice_val:", dice_val)


img_pr.shape (256, 256, 3)
img_mask.shape (256, 256, 3)
(256, 256)
(256, 256)
Dice Similarity A_0001.png : 0.9103576588880312
intersection: 45994.0
dice_val: 0.9103576588880312


In [54]:
path_pr = "/run/media/j/tmp_ntfs/0_t_mest_bkp/tests/Segmentacao Linha Plantio CNN/Teste_01E/result-images/A_0001.png"
path_mask = "/run/media/j/tmp_ntfs/0_t_mest_bkp/tests/Segmentacao Linha Plantio CNN/Recortes/Base_A_mask/A_0001.png"

img_pr = cv2.imread(path_pr) # (256, 256, 3)
img_mask = cv2.imread(path_mask) # (256, 256, 3)

print("img_pr.shape", img_pr.shape)
print("img_mask.shape", img_mask.shape)


img_pr = cv2.imread(path_pr, cv2.IMREAD_GRAYSCALE) # (256, 256)
img_mask = cv2.imread(path_mask, cv2.IMREAD_GRAYSCALE) # (256, 256)

print("img_pr.shape", img_pr.shape)
print("img_mask.shape", img_mask.shape)


img_pr.shape (256, 256, 3)
img_mask.shape (256, 256, 3)
img_pr.shape (256, 256)
img_mask.shape (256, 256)


In [ ]:
count = 0
for i in range(256):
    for j in range(256):
        count += 1
        print("count:", count, " img_pr[", i, "][", j, "]", img_pr[i][j])


# VI

In [10]:
import cv2
import numpy as np

img = cv2.imread("/media/sda2/home/j/Downloads/0del/00/iv/Recortes/E/A_0001.png")
print(type(img))
print(img.dtype)
print(img.shape)

#print(img)

<class 'numpy.ndarray'>
uint8
(256, 256, 3)


In [11]:
def split_RGB_channel(img): # return RGB channels
    # opencv reads the images as BGR instead of RGB
    B, G, R = cv2.split(img)

    # Convert to float
    # Inf whe sum is more then 255
    # RuntimeWarning: divide by zero encountered in true_divide
    R = R.astype('float32')
    G = G.astype('float32')
    B = B.astype('float32')

    return R, G, B

def normalized_RGB(img): # return normalized values for each RGB channel
    R, G, B = split_RGB_channel(img)

    # 24 bits image, 8 bits for each color, has 255 (2^8) as max value
    Rn = R/255.0
    Gn = G/255.0
    Bn = B/255.0

    return Rn, Gn, Bn

def chromatic_coordinates(img): # Return cromatic coordinates for each RGB channel
    Rn, Gn, Bn = normalized_RGB(img)

    ALLn = Rn + Gn + Bn

    r = Rn / ALLn
    g = Gn / ALLn
    b = Bn / ALLn

    return r, g, b

# 01 VARI  Visible Atmospherically Resistant Index
# 02 ExG   Excess Green Index
# 03 ExR   Excess Red Vegetation Index
# 04 ExB   Excess Blue Vegetation Index
# 05 EXGR  Excess Green minus Excess Red
# 06 GRVI  Green Red Vegetation Index
# 07 MGRVI Modified Green Red Vegetation Index
# 08 GLI   Green Leaf Index
# 09 RGBVI Red Green Blue Vegetation Index
# 10 IKAW  Kawashima Index

def calc_VI_01_VARI(img): # calculate VARI
    r, g, b = chromatic_coordinates(img)

    vi_01_vari = (g - r) / (g + r - b)
    return vi_01_vari

def calc_VI_02_ExG(img): # calculate ExG
    r, g, b = chromatic_coordinates(img)

    vi_02_ExG = 2*g - r - b
    return vi_02_ExG

def calc_VI_03_ExR(img): # calculate ExR
    R, G, B = split_RGB_channel(img)

    vi_03_ExR = (1.4 * R - G) / ( R + G + B)
    return vi_03_ExR

def calc_VI_04_ExB(img): # calculate ExB
    R, G, B = split_RGB_channel(img)

    vi_04_ExB = (1.4 * B - G) / ( R + G + B)
    return vi_04_ExB

def calc_VI_05_ExGR(img): # calculate ExGR
    r, g, b = chromatic_coordinates(img)

    vi_02_ExG = calc_VI_02_ExG(img)
    vi_03_ExR = calc_VI_03_ExR(img)

    vi_05_ExGR = vi_02_ExG - vi_03_ExR
    return vi_05_ExGR

def calc_VI_06_GRVi(img): # calculate GRVI
    R, G, B = split_RGB_channel(img)

    vi_06_GRVI = (G - R) / (G + R)
    return vi_06_GRVI

def calc_VI_07_MGRVI(img): # calculate MGRVI
    R, G, B = split_RGB_channel(img)

    vi_07_MGRVI = (G ** 2 - R ** 2) / (G ** 2 + R ** 2)
    return vi_07_MGRVI

def calc_VI_08_GLI(img): # calculate GLI
    r, g, b = chromatic_coordinates(img)

    vi_08_GLI = (2*g - r - b) / (-r - b)
    return vi_08_GLI

def calc_VI_09_RGBVI(img): # calculate RGBVI
    R, G, B = split_RGB_channel(img)

    vi_09_RGBVI = (G ** 2 - B * R) / (G ** 2 + B * R)
    return vi_09_RGBVI

def calc_VI_10_IKAW(img): # calculate IKAW
    R, G, B = split_RGB_channel(img)

    vi_10_IKAW = (R - B) / (R + B)
    return vi_10_IKAW


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def return_vi_by_number(viNum, img):
    if viNum == 1:
        vi = calc_VI_01_VARI(img)
    elif viNum == 2:
        vi = calc_VI_02_ExG(img)
    elif viNum == 3:
        vi = calc_VI_03_ExR(img)
    elif viNum == 4:
        vi = calc_VI_04_ExB(img)
    elif viNum == 5:
        vi = calc_VI_05_ExGR(img)
    elif viNum == 6:
        vi = calc_VI_06_GRVi(img)
    elif viNum == 7:
        vi = calc_VI_07_MGRVI(img)
    elif viNum == 8:
        vi = calc_VI_08_GLI(img)
    elif viNum == 9:
        vi = calc_VI_09_RGBVI(img)
    elif viNum == 10:
        vi = calc_VI_10_IKAW(img)

    return vi

def plot_vis_10(cmap="viridis"): # default cmap="viridis"
    rows = 2
    cols = 5

    #fig, axes = plt.subplots(nm_img_to_plot, cols, figsize=(cols * figsize, nm_img_to_plot * figsize), squeeze=False)
    fig, axes = plt.subplots(rows, cols, figsize=(15 * rows, 2.5 * cols))

    namesVI = ["01 VARI", "02 ExG", "03 ExR", "04 ExB", "05 EXGR",
               "06 GRVI", "07 MGRVI", "08 GLI", "09 RGBVI", "10 IKAW"]

    posX = 0
    posY = 0
    for viNum in range(1, 11):
        #print ("viNum:", viNum)
        print(namesVI[viNum - 1])

        vi = return_vi_by_number(viNum, img)

        print("max", np.max(vi), "min", np.min(vi))
        print("dtype", vi.dtype, "shape", vi.shape)

        #print("axes[",posX, posY,"].")
        axes[posX, posY].set_title(namesVI[viNum - 1], fontsize=15)

        axes[posX, posY].set_axis_off()

        #axes[posX, posY].imshow(vi)
        axes[posX, posY].imshow(vi, cmap=cmap)

        posY += 1
        if posY == cols:
            posY = 0
            posX += 1

    # set the spacing between subplots
    #fig.tight_layout(pad=0, h_pad=None, w_pad=None, rect=None)
    plt.show()

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.show()

plot_vis_10()

plot_vis_10(cmap="gray")

# https://docs.opencv.org/4.x/d3/d50/group__imgproc__colormap.html
plot_vis_10(cmap="turbo")


## Tests of errors

In [107]:
iv = calc_IV_03_ExR(img)

print(np.max(iv))
print(np.min(iv))

def printInfos():
    for i in range(256):
        for j in range(256):
            #print(iv[i, j], end=" ")
            if iv[i, j] == np.inf:
                print("i:", i, "j:", j, "img[i,j]:", img[i,j], "iv[i,j]", iv[i, j])
                print("\n-------------------------------------------------------------------------")
                input()
    print("done!")

printInfos()
#iv[iv < 0] = 0

0.24390244
0.03150684
done!


In [74]:
print(img[1, 172])

B = 100
G = 99
R = 57

print("t:", R + G + B)
print("b:", (1.4 * R - G))

res = (1.4 * R - G) / ( R + G + B)
print(res)


[ 57  99 100]
t: 256
b: -19.200000000000003
-0.07500000000000001


In [29]:
a = np.array([6, 2, 1, 0])
b = np.array([3, 1, 0, 1])

c = a / b

print(c)

d = a * b
print(d)

B = np.array(img[1, 172, 0])
G = np.array(img[1, 172, 1])
R = np.array(img[1, 172, 2])


R = R.astype('float64')
G = G.astype('float64')
B = B.astype('float64')

print("BGR", B, G, R)

t = (1.4 * R - G)
print("t", t)
b = (R + G) + B
print("b", b)
print(type(b))

res = (1.4 * R - G) / ( R + G + B)
print(res)

[ 2.  2. inf  0.]
[18  2  0  0]
BGR 57.0 99.0 100.0
t 41.0
b 256.0
<class 'numpy.float64'>
0.16015625


/tmp/ipykernel_28665/2793365588.py:4: RuntimeWarning: divide by zero encountered in true_divide
  c = a / b
